logger.sh and cronlogger enhancements
- logger.sh has been modified to be multiline, with a verbose header.
- cronlogger has been modified to use logger.sh, store more information
  in the token, and the token is retained after the job ends.

diff --git a/bin/cronlogger b/bin/cronlogger
--- a/bin/cronlogger
+++ b/bin/cronlogger
@@ -25,8 +25,7 @@ Options:
 Environment Variables:
   WORKDIR               The default directory under with logs and tokens are
                         created.  Logs are created under \$WORKDIR/log and the
-                        tokens under \$WORKDIR/token.  The token is removed
-                        upon the successful termination of COMMAND.
+                        tokens under \$WORKDIR/token.
 
 Files:
   \$WORKDIR/log/JOBNAME-YYYYMMDD_hh:mm:ss.log
@@ -47,35 +46,37 @@ EOF
 # PROGRAM BEGINS HERE
 
 source "getopt.sh" || exit 1
+source "logger.sh" || exit 1
 
 SCRIPTNAME=$(basename -- "$BASH_SOURCE")
-SCRIPTSTART=$(date)
 TOKENDIR=$WORKDIR/token
 LOGDIR=$WORKDIR/log
+STARTED=$(date +%s)
 TIMEOUT=""
+LOGGER_ENABLE+=" CRONJOB"
 
 
 function main() {
     local OPTOPT OPTARG
-    local logfile
+    local exitcode=0
 
     # Process options
     while getopt-sh "t:h" "timeout:,help" "$@"; do
         case "$OPTOPT" in
-            -t|--timeout)  TIMEOUT=$(date -d "$SCRIPTSTART + $OPTARG") ;;
+            -t|--timeout)  TIMEOUT=$(date -d "$OPTARG" +%s) ;;
             -h|--help)     usage && exit 0  ;;
             *)             errcount=$((errcount+1)) ;;
         esac
     done
 
     if (( ${#OPTARG[@]} != 2 )); then
-        echo "Expected 2 arguments, got ${#OPTARG[@]}" 1>&2
+        printf "Expected 2 arguments, got %s\n" "${#OPTARG[@]}" 1>&2
         errcount=$((errcount+1))
     fi
 
     # Sanity check
     if (( errcount )); then
-        echo "Type '${SCRIPTNAME} -h' for help." 1>&2
+        printf "Type '%s -h' for help\n" "$SCRIPTNAME" 1>&2
         exit 1
     fi
 
@@ -86,7 +87,15 @@ function main() {
     trap '__on_exit' EXIT
 
     # Do my thing
-    cronlogger "${OPTARG[@]}"
+    cronlogger "${OPTARG[@]}" || exitcode=$?
+
+    # Restore the signal handlers
+    trap - TERM
+    trap - HUP
+    trap - INT
+    trap - EXIT
+
+    return "$exitcode"
 }
 
 
@@ -95,19 +104,21 @@ function __on_signal() {
     local signum=$(kill -l $signal)
 
     # Record the cause of termination
-    echo "Caught $signal"
+    logger WARNING "Caught SIG${signal}"
 
-    case "$signal" in
-        INT)    # SIGINT should send signal to itself to terminate.  See
-                # http://mywiki.wooledge.org/SignalTrap#Special_Note_On_SIGINT_and_SIGQUIT
-                trap - $signal
-                kill -s $signal $$
-                ;;
+    # Restore the signal handlers
+    trap - TERM
+    trap - HUP
+    trap - INT
 
-        *)      trap - $signal
-                exit $((128 + signum))
-                ;;
-    esac
+    # SIGINT should send signal to itself to terminate.  See
+    # http://mywiki.wooledge.org/SignalTrap#Special_Note_On_SIGINT_and_SIGQUIT
+    if [[ "$signal" == "INT" ]]; then
+        kill -s $signal $$
+    fi
+
+    # Terminate
+    exit $((128 + signum))
 }
 
 
@@ -122,7 +133,7 @@ function cronlogger() {
     local command=$2
     local logfile=$(logname "$jobname")
 
-    echo "$jobname cronjob logfile is $logfile"
+    printf "%s cronjob logfile is %s\n" "$jobname" "$logfile"
 
     mkdir -p "$(dirname "$logfile")" \
     && run "$jobname" "$command" >& "$logfile"
@@ -131,32 +142,44 @@ function cronlogger() {
 
 function logname() {
     local jobname=$1
-    local datetime=$(date -d "$SCRIPTSTART" "+%Y%m%d_%H:%M:%S")
+    local datetime=$(date -d "@${STARTED}" "+%Y%m%d_%H:%M:%S")
 
-    echo "${LOGDIR}/${jobname}-${datetime}.log"
+    printf "%s/%s-%s.log" "$LOGDIR" "$jobname" "$datetime"
 }
 
 
 function run() {
     local jobname=$1
     local command=$2
+    local tokenfile=$(tokenname)
     local exitcode=0
+    local pid
 
-    echo "$jobname started at $(date)"
+    logger INFO "${jobname} started"
 
+    # Create the token
     if ! mktoken "$jobname"; then
-        echo "Unable to create token, terminating." 1>&2
+        logger ERROR "Unable to create token, terminating"
         exit 1
     fi
 
     # Run the command
-    bash <<<$command || exitcode=$?
+    bash <<<"$command" >& >(logger CRONJOB) & pid=$!
+    printf "JOB_PID=%s\n" "$pid" >> "$tokenfile"
 
+    # Wait
+    wait $pid
+    exitcode=$?
+    (
+        printf "JOB_EXITCODE=%s\n" "$exitcode"
+        printf "JOB_EXITED=%s\n" "$(date +%s)"
+    ) >> "$tokenfile"
+
+    # Report status
     if (( exitcode == 0 )); then
-        echo "$jobname terminated successfully at $(date)"
-        rmtoken "$jobname"
+        logger INFO "${jobname} terminated successfully"
     else
-        echo "$jobname terminated with exit code $exitcode at $(date)"
+        logger INFO "${jobname} terminated with exit code ${exitcode}"
     fi
 
     return $exitcode
@@ -165,19 +188,20 @@ function run() {
 
 function mktoken() {
     local jobname=$1
-    local tokenfile="${TOKENDIR}/${jobname}.token"
+    local tokenfile=$(tokenname)
 
     mkdir -p "$(dirname "$tokenfile")" \
     && rm -f "$tokenfile"              \
-    && echo "$TIMEOUT" > "$tokenfile"
+    && (
+        printf "JOB_NAME=%s\n" "$jobname"
+        printf "JOB_STARTED=%s\n" "$STARTED"
+        printf "JOB_TIMEOUT=%s\n" "$TIMEOUT"
+    ) > "$tokenfile"
 }
 
 
-function rmtoken() {
-    local jobname=$1
-    local tokenfile="${TOKENDIR}/${jobname}.token"
-
-    rm -f "$tokenfile"
+function tokenname() {
+    printf "%s\n" "${TOKENDIR}/${jobname}.token"
 }
 
 
